[
  {
    conditionOfPart: "Used",
    description: "Toyota Rear Bumper model T1wwwwww",
    id: 1235,
    image:
      "https://firebasestorage.googleapis.com/v0/b/auto-parts-app.appspot.com/o/products%2F71ws8XPJZkL-removebg-preview%202.png?alt=media&token=aa866788-2273-4bc0-8062-4ef5def8d78a",
    make: "Toyota",
    makeId: 1,
    model: "Corolla",
    modelId: 1,
    newArrival: "true",
    price: "35000",
    productName: "Toyota Rear Bumpers T1",
    subCategory: 1,
    yearId: 1,
  },
  {
    conditionOfPart: "New",
    description: "Toyota Rear Bumper model T3",
    id: 1237,
    image:
      "https://firebasestorage.googleapis.com/v0/b/auto-parts-app.appspot.com/o/products%2Fcover-removebg-preview.png?alt=media&token=3702d05d-b757-4a56-b647-cad7f0fdab9c",
    make: "Toyota",
    makeId: 1,
    model: "Rav4",
    modelId: 3,
    newArrival: "true",
    price: "29000",
    productName: "Toyota Rear Bumpers T3",
    subCategory: 1,
    yearId: 7,
  },
  {
    conditionOfPart: "New",
    description: "Toyota Rear Bumper model T5",
    id: 1239,
    image:
      "https://firebasestorage.googleapis.com/v0/b/fir-learning-efa3c.appspot.com/o/Group%20280.png?alt=media&token=e37a0bd2-9a18-4c08-8d17-e12930e2be58",
    make: "Toyota",
    makeId: 1,
    model: "Camry",
    modelId: 2,
    newArrival: "true",
    price: "28000",
    productName: "Toyota Rear Bumpers T5",
    subCategory: 1,
    yearId: 6,
  },
  {
    conditionOfPart: "New",
    description: "Toyota Rear Bumper model T7",
    id: 1241,
    image:
      "https://firebasestorage.googleapis.com/v0/b/fir-learning-efa3c.appspot.com/o/Group%20280.png?alt=media&token=e37a0bd2-9a18-4c08-8d17-e12930e2be58",
    make: "Toyota",
    makeId: 1,
    model: "Corolla",
    modelId: 1,
    newArrival: "true",
    price: "27000",
    productName: "Toyota Rear Bumpers T7",
    subCategory: 1,
    yearId: 3,
  },
  {
    conditionOfPart: "New",
    description: "Toyota Rear Bumper model T9",
    id: 1243,
    image:
      "https://firebasestorage.googleapis.com/v0/b/fir-learning-efa3c.appspot.com/o/Group%20280.png?alt=media&token=e37a0bd2-9a18-4c08-8d17-e12930e2be58",
    make: "Toyota",
    makeId: 1,
    model: "Rav4",
    modelId: 3,
    newArrival: "true",
    price: "31000",
    productName: "Toyota Rear Bumpers T9",
    subCategory: 1,
    yearId: 8,
  },
];
